#!/bin/sh

mkdir -p opk/
git fetch --all
git merge upstream/branch-2-6-1
cd backends/platform/libretro/build
make clean
make -j16
/opt/FunKey-sdk/bin/arm-funkey-linux-musleabihf-strip scummvm_libretro.so
cp -f scummvm_libretro.so ../../../../opk/
cd -
cp -f icons/scummvm.png AUTHORS CONTRIBUTING.md COPYING COPYRIGHT NEWS.md README.md opk/

cd backends/platform/libretro/aux-data
./bundle_aux_data.bash
cd -
unzip backends/platform/libretro/aux-data/scummvm_tmp.zip -d opk/

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GMenu2X entry file plus other things
print '[Desktop Entry]
Name=ScummVM
Comment=ScummVM v2.6.1 for Libretro
Exec=picoarch ./scummvm_libretro.so
Icon=scummvm
Categories=games' > opk/scummvm.funkey-s.desktop

rm -f *.opk
mksquashfs opk/ scummvm_v2.6.1_funkey-s.opk -all-root -noappend -no-exports -no-xattrs

rm -rf opk/

rm -f backends/platform/libretro/aux-data/scummvm_tmp.zip
